cisagov/cyber.dhs.gov

pages/guide.md

This addition to the guide page should add clarity around DKIM requirements.

Added language about DKIM not being a requirement

---

pages/guide.md

Fixes #18, adds a section defining what second-level means and giving an example on how to interpret it.

Add second-level domain definition to FAQ

---

pages/guide.md

Addresses Issue #17, adds explanatory text on how authenticating subdomains should be considered.

Clarify how subdomains should be handled under BOD 18-01

---

pages/intro.md

Making the intro to email auth page a bit clearer.

Small revision to intro page

---

pages/15-01.md

Adding the issuance date to BOD 15-01

Date addition

---

pages/16-01.md
pages/16-02.md
pages/16-03.md
pages/17-01.md
pages/18-01.md

This change adds issuance dates to all BODs

Adding Dates to Rest of BODs

---

_data/navigation.yml
pages/17-01.md

From America, with love, this change fixes an unfortunate typographical error.

Spell Kaspersky correctly

---

README.md

https://github.com/uswds/uswds/blob/develop/docs/WHO_IS_USING_USWDS.md

fixed link to USWDS

---

pages/18-01.md

This update adds three questions:
* "How should DMARC be deployed?"
* "Why is `p=reject` required?"
* "Does using `p=reject` mean that leads or anonymous sources may not be able to send us emails?"
Addresses #29.
cc: @JoshuaStankus @FNR-BOD

Add 3 FAQs

---

pages/18-01.md

This changes fixes some broken links and adds a link to the RFC sections about DMARC reports.

Link {fix, add}

---

pages/18-01.md

This addition adds an FAQ for "What should be done with DMARC report data?"

Adding an FAQ for what to do with DMARC reports, Resources section add

---

package-lock.json
package.json
pages/18-01.md
pages/index.md

This update makes internal links relative and levels up dependencies.

December cleaning

---

pages/18-02.md

M-17-09 has been replaced by M-19-03. This change updates a note in BOD 18-02 and links to the updated memo.

Rescind M-17-09

---

_data/navigation.yml
pages/blog.md
pages/ed-19-01.md

This PR adds the Director's comments on ED 19-01.

Blog post addition on ED 19-01

---

pages/blog.md
pages/ed-19-01.md

This small change adds some headers in Markdown to allow for better targeted hyperlinks.

Header fix to ED 19-01

---

pages/20-01.md

We're all human, some more than others.

Fix 20-01 typo

---

pages/20-01-vdp-template.md
pages/20-01.md

Add VDP template in Markdown, v2

---

pages/20-01.md

This change extends the deadline for BOD 20-01 (draft) to Jan 10, 2020.

Extend deadline for 20-01 to Jan 10, 2020

---

assets/report/ed-20-04_script/CVE-2020-1472.ps1
assets/report/ed-20-04_script/README.md

Cyber at the speed of ~light~ lawyers.

Re-add 20-04 script

---

assets/report/ed-20-04_script/CVE-2020-1472.ps1

Resolves critical issue of "executing" misspelling

Typo correction in first comment

---

pages/20-01-vdp-template.md

As the language as of now can be vague, suggest changing to 'persistent command line access'.

Change 'command line access' to 'persistent command line access'

---

assets/report/ed-20-04_script/CVE-2020-1472.ps1

Add ability to use TLS with 20-04 script

---

pages/20-01.md

This change adds an FAQ about what the directive means by "good faith" and makes a few small edits to text + nav.

Add good faith FAQ + small revisions

---

_data/navigation.yml
pages/ed-21-01.md
pages/index.md

This change publishes Emergency Directive 21-01.

Post Emergency Directive 21-01

---

pages/ed-21-01.md

Supplemental Guidance V2 for 21-01

---

pages/ed-21-01.md

Reverts cisagov/cyber.dhs.gov#217

Revert "Supplemental Guidance V2 for 21-01"

---

pages/ed-21-01.md

updated with second supp guidance.

Supplemental Guidance V2

---

pages/ed-21-01.md

formatting change + adding document title

JoshuaStankus-Supp-Guidance-v2-Formatting-Update

---

pages/ed-21-01.md

Moving "For the purposes of ED 21-01 and associated supplemental guidance, a network is defined as any computer network with hosts that share either a logical trust or any account credentials with SolarWinds Orion." from part of Category 3 bullet in "Network Categorization" section to it's own line to mirror ED text.

Formatting change 21-01

---

pages/20-01.md

Testing merging with CD as well

Update Report Vulns FAQ

---

pages/ed-21-02.md

update to add ED 21-02 supplemental direction

Ed 21 02 supplemental direction

---

pages/22-01.md
pages/index.md

BOD 22-01 Staging

---

pages/22-01.md

Added FAQ.  All links and formatting appears correct, but please check before committing.
BTW, I think we should remove the "click here" text from the Resources and Contact Information - this is not the general convention anymore..

Add FAQ section to BOD 22-01.md

---

pages/15-01.md

testing out redirect on BOD 15-01 before trying the rest.

Testing Redirect Function
